# Códigos de eventos considerados obrigatórios para análise, conforme definição do projeto.
EVENTOS_PONTUACAO = [
 {
    "cod": "110",
    "nome": "Sessão Deliberativa",
    "descricao": "Sessão em plenário para votação de proposições. É a atividade máxima do mandato parlamentar.",
    "obrigatoriedade": "obrigatório",
    "pontuacao": 100,
    "categoria": "deliberação",
    "importancia": "Essencial para o processo legislativo",
  },
  {
    "cod": "112",
    "nome": "Reunião Deliberativa",
    "descricao": "Reunião de comissão para votar pareceres e projetos específicos.",
    "obrigatoriedade": "obrigatório",
    "pontuacao": 80,
    "categoria": "deliberação",
    "importancia": "Votação de matérias em comissão",
  },
  {
    "cod": "115",
    "nome": "Sessão Não Deliberativa Solene",
    "descricao": "Eventos protocolares para celebrar datas ou personalidades.",
    "obrigatoriedade": "institucional",
    "pontuacao": 20,
    "categoria": "representação",
    "importancia": "Importância diplomática e representativa",
  },
  {
    "cod": "118",
    "nome": "Trabalho de Comissões",
    "descricao": "Atividades internas de instrução e análise de projetos.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 40,
    "categoria": "participação",
    "importancia": "Análise técnica de proposições",
  },
  {
    "cod": "120",
    "nome": "Audiência Pública",
    "descricao": "Espaço de escuta da sociedade civil sobre temas de interesse público.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 50,
    "categoria": "participação",
    "importancia": "Diálogo com a sociedade",
  },
  {
    "cod": "122",
    "nome": "Tomada de Depoimento",
    "descricao": "Ato de ouvir autoridades ou testemunhas para fiscalização.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 65,
    "categoria": "fiscalização",
    "importancia": "Fiscalização do Executivo",
  },
  {
    "cod": "125",
    "nome": "Audiência Pública e Deliberação",
    "descricao": "Debate com a sociedade seguido de votação de matérias.",
    "obrigatoriedade": "obrigatório",
    "pontuacao": 85,
    "categoria": "deliberação",
    "importancia": "Deliberação com participação social",
  },
  {
    "cod": "130",
    "nome": "Seminário",
    "descricao": "Eventos de aprofundamento técnico sobre temas legislativos.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 30,
    "categoria": "participação",
    "importancia": "Capacitação técnica",
  },
  {
    "cod": "140",
    "nome": "Mesa Redonda",
    "descricao": "Debates formatados para troca de experiências técnicas.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 25,
    "categoria": "participação",
    "importancia": "Troca de conhecimento",
  },
  {
    "cod": "150",
    "nome": "Sessão Não Deliberativa de Debates",
    "descricao": "Sessão para debate de temas sem votação imediata.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 35,
    "categoria": "participação",
    "importancia": "Debate público de temas",
  },
  {
    "cod": "152",
    "nome": "Reunião de Debate",
    "descricao": "Reunião interna para discussão de proposições.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 30,
    "categoria": "participação",
    "importancia": "Discussão técnica",
  },
  {
    "cod": "155",
    "nome": "Visita Técnica",
    "descricao": "Atividade de fiscalização 'in loco' de obras ou órgãos públicos.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 60,
    "categoria": "fiscalização",
    "importancia": "Fiscalização presencial",
  },
  {
    "cod": "157",
    "nome": "Visita Oficial",
    "descricao": "Visita oficial a instituições ou localidades.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 45,
    "categoria": "representação",
    "importancia": "Representação institucional",
  },
  {
    "cod": "160",
    "nome": "Painel",
    "descricao": "Debate com especialistas sobre temas de interesse.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 25,
    "categoria": "participação",
    "importancia": "Discussão especializada",
  },
  {
    "cod": "170",
    "nome": "Simpósio",
    "descricao": "Eventos de aprofundamento técnico com múltiplos palestrantes.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 30,
    "categoria": "participação",
    "importancia": "Capacitação avançada",
  },
  {
    "cod": "175",
    "nome": "Sessão Preparatória - Posse",
    "descricao": "Sessão preparatória para posse de novos deputados.",
    "obrigatoriedade": "institucional",
    "pontuacao": 15,
    "categoria": "representação",
    "importancia": "Evento protocolar",
  },
  {
    "cod": "177",
    "nome": "Sessão Preparatória - Eleição",
    "descricao": "Sessão preparatória para eleição de órgãos da Casa.",
    "obrigatoriedade": "institucional",
    "pontuacao": 15,
    "categoria": "representação",
    "importancia": "Evento protocolar",
  },
  {
    "cod": "180",
    "nome": "Reunião de Instalação e Eleição",
    "descricao": "Reunião para instalação e eleição de comissão.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 20,
    "categoria": "representação",
    "importancia": "Organização interna",
  },
  {
    "cod": "185",
    "nome": "Reunião de Instalação",
    "descricao": "Reunião para instalação de comissão ou órgão.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 15,
    "categoria": "representação",
    "importancia": "Organização interna",
  },
  {
    "cod": "190",
    "nome": "Reunião de Eleição",
    "descricao": "Reunião para eleição de membros de comissão.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 15,
    "categoria": "representação",
    "importancia": "Organização interna",
  },
  {
    "cod": "191",
    "nome": "Comissão Geral",
    "descricao": "Debate no plenário com presença de ministros ou especialistas.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 50,
    "categoria": "participação",
    "importancia": "Debate de temas relevantes",
  },
  {
    "cod": "194",
    "nome": "Debate",
    "descricao": "Debate entre deputados sobre tema específico.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 35,
    "categoria": "participação",
    "importancia": "Discussão parlamentar",
  },
  {
    "cod": "195",
    "nome": "Outro Evento",
    "descricao": "Eventos diversos não classificados nas categorias anteriores.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 10,
    "categoria": "participação",
    "importancia": "Evento diverso",
  },
  {
    "cod": "196",
    "nome": "Diligência",
    "descricao": "Investigação direta realizada por membros de comissões (ex: CPIs).",
    "obrigatoriedade": "facultativo",
    "pontuacao": 70,
    "categoria": "fiscalização",
    "importancia": "Investigação parlamentar",
  },
  {
    "cod": "197",
    "nome": "Sessão de Eleição",
    "descricao": "Sessão para eleição de órgãos da Casa.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 20,
    "categoria": "representação",
    "importancia": "Evento protocolar",
  },
  {
    "cod": "198",
    "nome": "Palestra",
    "descricao": "Apresentação de especialista sobre tema específico.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 20,
    "categoria": "participação",
    "importancia": "Capacitação",
  },
  {
    "cod": "199",
    "nome": "Conferência",
    "descricao": "Conferência sobre tema de interesse legislativo.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 25,
    "categoria": "participação",
    "importancia": "Capacitação avançada",
  },
  {
    "cod": "200",
    "nome": "Ato Solene de Instalação",
    "descricao": "Ato solene para instalação de órgão ou comissão.",
    "obrigatoriedade": "institucional",
    "pontuacao": 15,
    "categoria": "representação",
    "importancia": "Evento protocolar",
  },
  {
    "cod": "201",
    "nome": "Reunião",
    "descricao": "Reunião geral de órgão ou comissão.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 25,
    "categoria": "participação",
    "importancia": "Reunião administrativa",
  },
  {
    "cod": "202",
    "nome": "Sessão Solene",
    "descricao": "Sessão solene para homenagens e eventos especiais.",
    "obrigatoriedade": "institucional",
    "pontuacao": 20,
    "categoria": "representação",
    "importancia": "Evento protocolar",
  },
  {
    "cod": "203",
    "nome": "Sessão de Debates",
    "descricao": "Sessão dedicada a debates sobre temas específicos.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 40,
    "categoria": "participação",
    "importancia": "Debate parlamentar",
  },
  {
    "cod": "204",
    "nome": "Sessão Deliberativa",
    "descricao": "Outra sessão deliberativa para votações.",
    "obrigatoriedade": "obrigatório",
    "pontuacao": 100,
    "categoria": "deliberação",
    "importancia": "Votação de proposições",
  },
  {
    "cod": "205",
    "nome": "Teste do Painel Eletrônico",
    "descricao": "Teste técnico do sistema de votação.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 5,
    "categoria": "participação",
    "importancia": "Teste técnico",
  },
  {
    "cod": "206",
    "nome": "Reunião Técnica",
    "descricao": "Reunião para discussão técnica de temas específicos.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 25,
    "categoria": "participação",
    "importancia": "Discussão técnica",
  },
  {
    "cod": "207",
    "nome": "Reunião de Comparecimento de Ministro(a)",
    "descricao": "Reunião com presença de ministro para prestação de contas.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 55,
    "categoria": "fiscalização",
    "importancia": "Fiscalização do Executivo",
  },
  {
    "cod": "208",
    "nome": "Evento Técnico",
    "descricao": "Evento para discussão de temas técnicos e legislativos.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 20,
    "categoria": "participação",
    "importancia": "Capacitação técnica",
  },
  {
    "cod": "209",
    "nome": "Homenagem",
    "descricao": "Evento de homenagem a personalidades ou instituições.",
    "obrigatoriedade": "institucional",
    "pontuacao": 15,
    "categoria": "representação",
    "importancia": "Evento protocolar",
  },
  {
    "cod": "210",
    "nome": "Tomada de Depoimento e Deliberação",
    "descricao": "Ato de ouvir autoridades ou testemunhas com poder de decisão imediata.",
    "obrigatoriedade": "obrigatório",
    "pontuacao": 90,
    "categoria": "deliberação",
    "importancia": "Fiscalização com votação",
  },
  {
    "cod": "211",
    "nome": "Tomada de Depoimento e Audiência Pública",
    "descricao": "Combinação de depoimento com audiência pública.",
    "obrigatoriedade": "facultativo",
    "pontuacao": 60,
    "categoria": "participação",
    "importancia": "Fiscalização com participação social",
  },
  {
    "cod": "212",
    "nome": "Tom. Depoimento, Aud. Pública e Delib.",
    "descricao": "Combinação de depoimento, audiência pública e deliberação.",
    "obrigatoriedade": "obrigatório",
    "pontuacao": 95,
    "categoria": "deliberação",
    "importancia": "Fiscalização completa com votação",
  },
]